version: '3.1'
services:
  bluebell:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/dongfg/bluebell
    container_name: bluebell
    restart: always
    env_file:
      - ../env/bluebell.env
    ports:
      - 20000:20000
    networks:
      server:
        aliases:
          - bluebell
networks:
  server:
    external: true